### ISSUE TITLE
CAn I Help

### ISSUE THREAD

**Issue by RedMAngo22** [twitchbot-discord/twitchbot-discord.github.io#1]

**Comment by Nanomotion** [comment]
No, this project is single-person right now.

**Comment by Nanomotion** [comment]
If you'd like to help with the public beta, you can add TwitchBot to your server via https://discordapp.com/oauth2/authorize?client_id=375805687529209857&scope=bot&permissions=18496

**Comment by RedMAngo22** [comment]
i have added. what are commands

**Comment by Nanomotion** [comment]
Type `twitch help` to see a list.
